apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-http
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---


apiVersion: v1
kind: Service
metadata: 
  name: http-webserver-service
  labels:
    ws: httpserver-service
spec:
  ports:
    - port: 8085
      targetPort: 80
      nodePort: 9222
  selector:
    ws: httpserver-service
  type: NodePort
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-web-server
  labels:
    ws: httpserver-service
spec:
  replicas: 3
  selector:
    matchLabels:
      ws: httpserver-service
  strategy:
   type: RollingUpdate  #This is due to above mentioned rsns
  template:
    metadata:
      labels: 
        app: webserver
    spec:
      containers:
      - image: httpd
        name: http-web-server
        ports:
        - containerPort: 9111
          name: http-port
        volumeMounts:
        - name: pvc-http
          mountPath: /usr/local/apache2/htdocs/
        volumes:
          - name: pvc-http
            persistentVolumeClaim:
              
               claimName: pvc-http
