apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---


apiVersion: v1
kind: Service
metadata:
  name: php-webserver-service
  labels:
    ws: phpserver-service
spec:
  ports:
    - port: 8090
      targetPort: 90
      nodePort: 31115
  selector:
    ws: phpserver-service
  type: NodePort
___


apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web-server
  labels:
    ws: phpserver-service
spec:
  replicas: 3
  selector:
    matchLabels:
      ws: phpserver-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        ws: phpserver-service
    spec:
      containers: 
      - image: vimal13/apache-webserver-php
        name: php-web-server
        ports:
        -  containerPort: 80
        name: php-port
        volumeMounts:
        - name: pvc-php
          mountPath: /var/www/html
      volumes:
      - name: pvc-php
        persistentVolumeClaim:
          
          claimName: pvc-php
